pointwest-kt-mvc/Models/ErrorViewModel.cs
namespace pointwest_kt_mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

pointwest-kt-mvc/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;

namespace pointwest_kt_mvc.Controllers
{
    public class CoursesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateCourse()
        {
            return View();
        }
    }
}

pointwest-kt-mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using pointwest_kt_mvc.Models;
using System.Diagnostics;

namespace pointwest_kt_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

pointwest-kt-mvc/Views/Courses/CreateCourse.cshtml
@{
    ViewData["Title"] = "Create Course";
}

<h1>Create New Course</h1>
<br />

<table border="0" cellpadding="5" cellspacing="0" width="600">
    <tr>
        <td>
            <label for="CourseTitle">Course Title:</label>
        </td>
        <td>
            <input name="CourseTitle" type="text" maxlength="60" style="width:100%;max-width: 300px;" />
        </td>
    </tr>
    <tr>
        <td>
            <label for="Stack">Stack:</label>
        </td>
        <td>
            <select name="Stack" type="text" maxlength="60" style="width:100%;max-width: 300px;">
                <option value="empty"></option>
                <option value="mern">MERN Stack</option>
                <option value="mean">MEAN Stack</option>
                <option value="django">Django Stack</option>
                <option value="rails">Rails</option>
                <option value="lamp">LAMP Stack</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>
            <label for="Description">Description:</label>
        </td>
        <td>
            <input name="Description" type="text" maxlength="43" style="width: 100%; max-width: 300px;" />
        </td>
    </tr>
    <tr>
        <td>
            <label for="Thumbnail">Thumbnail:</label>
        </td>
        <td>
            <input name="Thumbnail" type="text" maxlength="43" style="width: 100%; max-width: 300px;" />
        </td>
    </tr>
    <tr>
        <td>
            <label for="Price">Price:</label>
        </td>
        <td>
            <input name="Price" type="text" maxlength="43" style="width: 100%; max-width: 300px;" />
        </td>

</table>
<br />
<button name="Create" type="submit" maxlength="43" style="width: 100%; max-width: 300px; margin-left:210px; background-color:gray">
    Create
</button>

pointwest-kt-mvc/Views/Courses/Index.cshtml
@{
    ViewData["Title"] = "Courses Page";
}

<div class="text-center mb-5">
    <h1 class="display-4">
        Welcome to LaZuitt
    </h1>
    <br />
    <h3>Hello, Admin Judy</h3>
</div>

<div class="d-flex justify-content-between mb-3">
    <h2 class="d-inline">Courses Available</h2>
    <button class="btn btn-secondary text-light">
        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="CreateCourse">
            Create Course
        </a>
    </button>
</div>

<div class="row d-flex justify-content-between">
    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>ASP.NET</h3>
        <img class="img-fluid h-50" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMOH00P2p0cF3CtYyLLUp_7yTJsoqpwIyxeUihYWnOszvwSbFcJbyv3NleB4ackTfap2I&usqp=CAU" />

        <p>ASP is a development framework for building web pages.</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>Python</h3>
        <img class="img-fluid h-50" src="https://i.pinimg.com/originals/a8/53/14/a8531424a5fac660e4261f72ca817141.png" />

        <p>Python can be used on a server to create web applications.</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>Django</h3>
        <img class="img-fluid h-50" src="https://youteam.io/blog/wp-content/uploads/2022/06/django-icon-0.png" />

        <p>Django is a Python framework that makes it easier to create websites using Python.</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>JavaScript</h3>
        <img class="img-fluid h-50" src="https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png" />

        <p>JavaScript is the most known programming language of the web</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

</div>

pointwest-kt-mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="padding-bottom: 100px">
    <h1 class="display-4">Welcome to LaZuitt</h1>
    <br />
</div>

<div class="text-center">
    <button style="float: center; background-color: #e1f5fe; border-radius: 10px">
        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">
            Manage Courses
        </a>
    </button>
</div>

pointwest-kt-mvc/Views/Settings/Index.cshtml
@{
    ViewData["Title"] = "Settings";
}

pointwest-kt-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Judy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pointwest_kt_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Judy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - pointwest_kt_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>